# Generated by Django 4.2.6 on 2023-11-28 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_item_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
    ]
